CREATE TABLE IF NOT EXISTS CITY
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city VARCHAR                                 NOT NULL,
    CONSTRAINT pk_city PRIMARY KEY (id),
    CONSTRAINT UQ_CITY UNIQUE (city)
);

CREATE TABLE IF NOT EXISTS ADDRESSES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_id         BIGINT                                  NOT NULL,
    street          VARCHAR                                 NOT NULL,
    house_number    INTEGER                                 NOT NULL,
    building_number INTEGER,
    letter          VARCHAR,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT UQ_ADDRESSES UNIQUE (city_id, street, house_number, building_number, letter),
    CONSTRAINT FK_ADDRESSES_ON_CITY FOREIGN KEY (city_id) REFERENCES city (id)
);

CREATE TABLE IF NOT EXISTS REQUISITES
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id BIGINT,
    index      INTEGER,
    phone      VARCHAR,
    fax        VARCHAR,
    email      VARCHAR,
    CONSTRAINT pk_requisites PRIMARY KEY (id),
    CONSTRAINT FK_DEPARTMENTS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE IF NOT EXISTS ORGANIZATIONS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization            VARCHAR                                 NOT NULL,
    short_name_organization VARCHAR                                 NOT NULL,
    requisites_id           BIGINT,
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT UQ_ORGANIZATIONS UNIQUE (organization),
    CONSTRAINT FK_ORGANIZATIONS_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);

CREATE TABLE IF NOT EXISTS BRANCHES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch            VARCHAR                                 NOT NULL,
    short_name_branch VARCHAR                                 NOT NULL,
    requisites_id     BIGINT,
    organization_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_branch PRIMARY KEY (id),
    CONSTRAINT UQ_BRANCHES UNIQUE (branch),
    CONSTRAINT FK_BRANCHES_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id),
    CONSTRAINT FK_BRANCHES_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department            VARCHAR                                 NOT NULL,
    short_name_department VARCHAR                                 NOT NULL,
    department_number     INTEGER,
    requisites_id         BIGINT,
    branch_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT UQ_DEPARTMENTS UNIQUE (department, department_number),
    CONSTRAINT FK_DEPARTMENTS_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);

CREATE TABLE IF NOT EXISTS BUILDINGS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_type VARCHAR                                 NOT NULL,
    login         VARCHAR,
    department_id BIGINT                                  NOT NULL,
    requisites_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_building PRIMARY KEY (id),
    CONSTRAINT UQ_BUILDINGS UNIQUE (building_type, login),
    CONSTRAINT FK_BUILDINGS_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);

CREATE TABLE IF NOT EXISTS CONTROL_TYPES
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_type_control       VARCHAR                                 NOT NULL,
    short_name_type_control VARCHAR                                 NOT NULL,
    CONSTRAINT pk_typeControl PRIMARY KEY (id),
    CONSTRAINT UQ_CONTROL_TYPES UNIQUE (name_type_control)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR                                 NOT NULL,
    patronymic      VARCHAR                                 NOT NULL,
    surname         VARCHAR                                 NOT NULL,
    post            VARCHAR                                 NOT NULL,
    requisites_id   BIGINT,
    organization_id BIGINT                                  NOT NULL,
    branch_id       BIGINT                                  NOT NULL,
    department_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEES UNIQUE (name, patronymic, surname),
    CONSTRAINT FK_EMPLOYEES_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id),
    CONSTRAINT FK_EMPLOYEES_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_EMPLOYEES_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENTS FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE TABLE IF NOT EXISTS MEASURING_TOOLS
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    toll                   VARCHAR                                 NOT NULL,
    model                  VARCHAR                                 NOT NULL,
    work_number            VARCHAR,
    purpose                VARCHAR,
    manufacturing          DATE,
    exploitation           DATE,
    manufacturer_id        BIGINT,
    measuring_range        VARCHAR,
    characteristics        VARCHAR,
    tool_owner_id          BIGINT                                  NOT NULL,
    verification_date      DATE,
    next_verification_date DATE,
    organization_id        BIGINT,
    certificate_number     VARCHAR,
    registry               VARCHAR,
    note                   VARCHAR,
    control_type_id        BIGINT                                  NOT NULL,
    employee_id            BIGINT,
    CONSTRAINT pk_measuringTool PRIMARY KEY (id),
    CONSTRAINT UQ_MEASURING_TOOL UNIQUE (toll, model, work_number),
    CONSTRAINT FK_MEASURING_TOOL_ON_ORGANIZATION
        FOREIGN KEY (manufacturer_id) REFERENCES organizations (id),
    FOREIGN KEY (tool_owner_id) REFERENCES organizations (id),
    FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_MEASURING_TOOL_ON_CONTROL_TYPES FOREIGN KEY (control_type_id) REFERENCES control_types (id),
    CONSTRAINT FK_MEASURING_TOOL_ON_EMPLOYEES FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS CERTIFICATES
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document_type      VARCHAR                                 NOT NULL,
    certificate_number VARCHAR                                 NOT NULL,
    control_type_id    BIGINT                                  NOT NULL,
    level              VARCHAR                                 NOT NULL,
    start_date         DATE                                    NOT NULL,
    end_date           DATE                                    NOT NULL,
    points             VARCHAR,
    organization_id    BIGINT                                  NOT NULL,
    employee_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_certificate PRIMARY KEY (id),
    CONSTRAINT UQ_CERTIFICATES UNIQUE (control_type_id, employee_id),
    CONSTRAINT FK_CERTIFICATE_ON_CONTROL_TYPES FOREIGN KEY (control_type_id) REFERENCES control_types (id),
    CONSTRAINT FK_CERTIFICATE_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_CERTIFICATE_ON_EMPLOYEES FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS LICENSES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id   BIGINT,
    branch_id         BIGINT,
    department_id     BIGINT,
    document_type     VARCHAR                                 NOT NULL,
    license_number    VARCHAR                                 NOT NULL,
    start_date        DATE                                    NOT NULL,
    end_date          DATE,
    issued_license_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_license PRIMARY KEY (id),
    CONSTRAINT UQ_LICENSES UNIQUE (organization_id, branch_id, department_id, document_type),
    CONSTRAINT FK_LICENSES_ON_ORGANIZATIONS
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    FOREIGN KEY (issued_license_id) REFERENCES organizations (id),
    CONSTRAINT FK_LICENSES_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT FK_LICENSES_ON_DEPARTMENTS FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE TABLE IF NOT EXISTS OBJECTS_TYPES
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object      VARCHAR                                 NOT NULL,
    orientation VARCHAR,
    CONSTRAINT pk_objectsType PRIMARY KEY (id),
    CONSTRAINT UQ_OBJECTS_TYPES UNIQUE (object, orientation)
);

CREATE TABLE IF NOT EXISTS OBJECTS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objects_type_id BIGINT                                  NOT NULL,
    model           VARCHAR,
    number          INTEGER,
    volume          INTEGER,
    building_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_objects PRIMARY KEY (id),
    CONSTRAINT UQ_OBJECTS UNIQUE (objects_type_id, building_id),
    CONSTRAINT FK_OBJECTS_ON_OBJECTS_TYPES FOREIGN KEY (objects_type_id) REFERENCES objects_types (id),
    CONSTRAINT FK_OBJECTS_ON_BUILDINGS FOREIGN KEY (building_id) REFERENCES buildings (id)
);

CREATE TABLE IF NOT EXISTS NORMS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    min_in_percent    FLOAT,
    min               FLOAT                                   NOT NULL,
    size_tolerance    FLOAT,
    measurement_error FLOAT                                   NOT NULL,
    CONSTRAINT pk_norm PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PLACES
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    place VARCHAR                                 NOT NULL,
    CONSTRAINT pk_place PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element   VARCHAR                                 NOT NULL,
    diameter  INTEGER,
    thickness FLOAT,
    CONSTRAINT pk_element PRIMARY KEY (id),
    CONSTRAINT UQ_ELEMENTS UNIQUE (element, diameter, thickness)
);

CREATE TABLE IF NOT EXISTS ELEMENTS_NORMS
(
    element_id BIGINT,
    norm_id    BIGINT,
    CONSTRAINT pk_element_of_defects PRIMARY KEY (element_id, norm_id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS_PLACES
(
    element_id BIGINT,
    place_id   BIGINT,
    CONSTRAINT pk_element_of_places PRIMARY KEY (element_id, place_id)
);

CREATE TABLE IF NOT EXISTS DEFECT_PARAMETERS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parameters_name VARCHAR                                 NOT NULL,
    CONSTRAINT pk_defectParameter PRIMARY KEY (id),
    CONSTRAINT UQ_DEFECT_PARAMETERS UNIQUE (parameters_name)
);

CREATE TABLE IF NOT EXISTS DEFECTS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    defect VARCHAR                                 NOT NULL,
    CONSTRAINT pk_defect PRIMARY KEY (id),
    CONSTRAINT UQ_DEFECTS UNIQUE (defect)
);

CREATE TABLE IF NOT EXISTS DEFECTS_DEFECT_PARAMETERS
(
    defect_id           BIGINT,
    defect_parameter_id BIGINT,
    CONSTRAINT pk_defects_of_defect_parameters PRIMARY KEY (defect_id, defect_parameter_id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTATIONS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    view   VARCHAR,
    number VARCHAR,
    title  VARCHAR                                 NOT NULL,
    CONSTRAINT pk_documentation PRIMARY KEY (id),
    CONSTRAINT UQ_DOCUMENTATIONS UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS OBJECT_PASSPORT_DATA_TEMPLATES
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_sequence_number VARCHAR                                 NOT NULL,
    data_name            VARCHAR                                 NOT NULL,
    CONSTRAINT pk_objectPassportDataTemplate PRIMARY KEY (id),
    CONSTRAINT UQ_OBJECT_PASSPORT_DATA_TEMPLATES UNIQUE (data_sequence_number, data_name)
);

CREATE TABLE IF NOT EXISTS OBJECTS_TYPE_DATA
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    objects_type_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_objectsTypeData PRIMARY KEY (id),
    CONSTRAINT FK_OBJECTS_TYPE_DATA_ON_OBJECTS_TYPES FOREIGN KEY (objects_type_id) REFERENCES objects_types (id)
);

CREATE TABLE IF NOT EXISTS OBJECTS_TYPE_DATA_ELEMENTS
(
    objects_type_data_id BIGINT,
    element_id           BIGINT,
    CONSTRAINT pk_objects_type_data_of_elements PRIMARY KEY (objects_type_data_id, element_id)
);

CREATE TABLE IF NOT EXISTS OBJECTS_TYPE_DATA_DEFECTS
(
    objects_type_data_id BIGINT,
    defect_id            BIGINT,
    CONSTRAINT pk_objects_type_data_of_defects PRIMARY KEY (objects_type_data_id, defect_id)
);

CREATE TABLE IF NOT EXISTS OBJECTS_TYPE_DATA_DOCUMENTATIONS
(
    objects_type_data_id BIGINT,
    documentation_id     BIGINT,
    CONSTRAINT pk_objects_type_data_of_documentations PRIMARY KEY (objects_type_data_id, documentation_id)
);

CREATE TABLE IF NOT EXISTS OBJECTS_TYPE_DATA_OBJECT_PASSPORT_DATA_TEMPLATES
(
    objects_type_data_id BIGINT,
    template_id          BIGINT,
    CONSTRAINT pk_objects_type_data_of_object_passport_data_templates PRIMARY KEY (objects_type_data_id, template_id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_passport PRIMARY KEY (id),
    CONSTRAINT FK_PASSPORTS_ON_OBJECTS FOREIGN KEY (object_id) REFERENCES objects (id)
);

CREATE TABLE IF NOT EXISTS SURVEYS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            VARCHAR                                 NOT NULL,
    survey          VARCHAR                                 NOT NULL,
    survey_number   VARCHAR                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    passport_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_survey PRIMARY KEY (id),
    CONSTRAINT UQ_SURVEYS UNIQUE (survey, survey_number, organization_id),
    CONSTRAINT FK_SURVEYS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_SURVEYS_ON_PASSPORTS FOREIGN KEY (passport_id) REFERENCES passports (id)
);

CREATE TABLE IF NOT EXISTS REPAIRS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            VARCHAR                                 NOT NULL,
    description     VARCHAR                                 NOT NULL,
    organization_id BIGINT,
    passport_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_repair PRIMARY KEY (id),
    CONSTRAINT UQ_REPAIRS UNIQUE (date, description, organization_id),
    CONSTRAINT FK_REPAIRS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT FK_REPAIRS_ON_PASSPORTS FOREIGN KEY (passport_id) REFERENCES passports (id)
);

CREATE TABLE IF NOT EXISTS DATA_PASSPORT_OF_OBJECTS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id BIGINT                                  NOT NULL,
    meaning     VARCHAR                                 NOT NULL,
    passport_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_dataPassportOfObject PRIMARY KEY (id),
    CONSTRAINT UQ_DATA_PASSPORT_OF_OBJECTS UNIQUE (template_id, meaning, passport_id),
    CONSTRAINT FK_DATA_PASSPORT_OF_OBJECTS_ON_OBJECT_PASSPORT_DATA_TEMPLATES
        FOREIGN KEY (template_id) REFERENCES object_passport_data_templates (id),
    CONSTRAINT FK_DATA_PASSPORT_OF_OBJECTS_ON_PASSPORTS FOREIGN KEY (passport_id) REFERENCES passports (id)
);

CREATE TABLE IF NOT EXISTS REPORTING_DOCUMENTS
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    document VARCHAR                                 NOT NULL,
    CONSTRAINT pk_reportingDocument PRIMARY KEY (id),
    CONSTRAINT UQ_REPORTING_DOCUMENTS UNIQUE (document)
);

CREATE TABLE IF NOT EXISTS WORKS_PERFORMED
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    work                  VARCHAR                                 NOT NULL,
    reporting_document_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_workPerformed PRIMARY KEY (id),
    CONSTRAINT UQ_WORKS_PERFORMED UNIQUE (work),
    CONSTRAINT FK_WORKS_PERFORMED_ON_REPORTING_DOCUMENTS FOREIGN KEY (reporting_document_id)
        REFERENCES reporting_documents (id)
);

CREATE TABLE IF NOT EXISTS APPLICATIONS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              DATE                                    NOT NULL,
    address_id        BIGINT                                  NOT NULL,
    object_id         BIGINT                                  NOT NULL,
    work_performed_id BIGINT                                  NOT NULL,
    comment           VARCHAR,
    CONSTRAINT pk_application PRIMARY KEY (id),
    CONSTRAINT UQ_APPLICATIONS UNIQUE (date, address_id, object_id),
    CONSTRAINT FK_APPLICATIONS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_APPLICATIONS_ON_OBJECTS FOREIGN KEY (object_id) REFERENCES objects (id),
    CONSTRAINT FK_APPLICATIONS_ON_WORKS_PERFORMED FOREIGN KEY (work_performed_id) REFERENCES works_performed (id)
);

CREATE TABLE IF NOT EXISTS APPLICATIONS_EMPLOYEES
(
    application_id BIGINT,
    employee_id    BIGINT,
    CONSTRAINT pk_application_of_employees PRIMARY KEY (application_id, employee_id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTS_INFORMATION
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              DATE                                    NOT NULL,
    address_id        BIGINT                                  NOT NULL,
    object_id         BIGINT                                  NOT NULL,
    work_performed_id BIGINT                                  NOT NULL,
    document_number   INTEGER                                 NOT NULL,
    employee_id       BIGINT,
    start_date         TIMESTAMP,
    end_date           TIMESTAMP,
    status            VARCHAR                                 NOT NULL,
    CONSTRAINT pk_documentInformation PRIMARY KEY (id),
    CONSTRAINT FK_DOCUMENTS_INFORMATION_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_DOCUMENTS_INFORMATION_ON_OBJECTS FOREIGN KEY (object_id) REFERENCES objects (id),
    CONSTRAINT FK_DOCUMENTS_INFORMATION_ON_WORKS_PERFORMED FOREIGN KEY (work_performed_id) REFERENCES works_performed (id),
    CONSTRAINT FK_DOCUMENTS_INFORMATION_ON_EMPLOYEES FOREIGN KEY (employee_id) REFERENCES employees (id)
);