CREATE TABLE IF NOT EXISTS CITY
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city VARCHAR                                 NOT NULL,
    CONSTRAINT pk_city PRIMARY KEY (id),
    CONSTRAINT UQ_CITY UNIQUE (city)
);

CREATE TABLE IF NOT EXISTS ADDRESSES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_id         BIGINT                                  NOT NULL,
    street          VARCHAR                                 NOT NULL,
    house_number    INTEGER                                 NOT NULL,
    building_number INTEGER,
    letter          VARCHAR,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT UQ_ADDRESSES UNIQUE (city_id, street, house_number),
    CONSTRAINT FK_ADDRESSES_ON_CITY FOREIGN KEY (city_id) REFERENCES city (id)
);

CREATE TABLE IF NOT EXISTS REQUISITES
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id BIGINT NOT NULL,
    index INTEGER,
    phone VARCHAR,
    fax   VARCHAR,
    email VARCHAR,
    CONSTRAINT pk_requisites PRIMARY KEY (id),
    CONSTRAINT FK_DEPARTMENTS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE IF NOT EXISTS ORGANIZATIONS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization            VARCHAR                                 NOT NULL,
    short_name_organization VARCHAR                                 NOT NULL,
    requisites_id           BIGINT,
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT UQ_ORGANIZATIONS UNIQUE (organization),
    CONSTRAINT FK_ORGANIZATIONS_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);

CREATE TABLE IF NOT EXISTS BRANCHES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch            VARCHAR                                 NOT NULL,
    short_name_branch VARCHAR                                 NOT NULL,
    requisites_id     BIGINT,
    organization_id BIGINT NOT NULL,
    CONSTRAINT pk_branch PRIMARY KEY (id),
    CONSTRAINT UQ_BRANCHES UNIQUE (branch),
    CONSTRAINT FK_BRANCHES_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id),
    CONSTRAINT FK_BRANCHES_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department            VARCHAR                                 NOT NULL,
    short_name_department VARCHAR                                 NOT NULL,
    department_number     INTEGER,
    requisites_id         BIGINT,
    branch_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT UQ_DEPARTMENTS UNIQUE (department, department_number),
    CONSTRAINT FK_DEPARTMENTS_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);

CREATE TABLE IF NOT EXISTS BUILDINGS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id    BIGINT                                  NOT NULL,
    building_type VARCHAR                                 NOT NULL,
    branch        VARCHAR                                 NOT NULL,
    login         VARCHAR,
    department_id BIGINT                                  NOT NULL,
    requisites_id BIGINT NOT NULL,
    CONSTRAINT pk_building PRIMARY KEY (id),
    CONSTRAINT UQ_BUILDINGS UNIQUE (building_type, branch, login),
    CONSTRAINT FK_BUILDINGS_ON_ADDRESSES FOREIGN KEY (address_id) REFERENCES addresses (id),
    CONSTRAINT FK_BUILDINGS_ON_REQUISITES FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);